# Generated by Django 2.1.5 on 2019-05-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('надо сделать', 'надо сделать'), ('сделано', 'сделано'), ('отменено', 'отменено')], default='надо сделать', max_length=25)),
            ],
        ),
    ]
